name: AListNativeUI
options:
  bundleIdPrefix: com.bp00qd
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
targets:
  AListNativeUI:
    type: application
    platform: iOS
    sources:
      - path: AListNativeUI
    dependencies:
      - framework: build/AListCore.xcframework
        embed: false
        link: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bp00qd.alist-native-ios
        PRODUCT_NAME: AListNative
        MARKETING_VERSION: "2.0.4"
        CURRENT_PROJECT_VERSION: "809"
        INFOPLIST_FILE: AListNativeUI/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_EMIT_LOC_STRINGS: YES
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: ""
        OTHER_LDFLAGS: "$(inherited) -lc++ -lresolv"
    scheme:
      gatherCoverageData: false
      testTargets: []
      run:
        config: Debug
      archive:
        config: Release
